ACCELERATE:
  RUN_NAME: "no_app_trainq"
  EVAL_PERIOD: 10

MODEL:
  UNET_CONFIG:
    TRAIN_CROSS_ATTN_Q: True

  APPEARANCE_GUIDANCE_CONFIG:
    ATTN_RESIDUAL_BLOCK_IDX: []
    INNER_DIMS: []
    CTX_DIMS: []
    EMBED_DIMS: []
    HEADS: []
